---
title: "prairiestrips/groundwater/data-raw/waterquality/ README"
author: "witte"
date: "3/15/2019"
output: html_document
---
This folder contains the files we receive from the ISU water quality lab. Unfortunately, the spreadsheet formats do change from year to year, but this occurs at the water quality lab and is not in our control. Each year's folder contains at least one "groundwater.csv" and one "groundwater_codes.csv" file.  
  
The "groundwater.csv" files' 3rd row contains the column id's. The column id's can vary by year, but they do describe the units of measurement, if any.  
  
The "groundwater_codes.csv" files' 3rd row contains the column id's. The column id's can vary by year, but they usually have some form of the following variables:  
  
* year (4 digit year)
* month (1-12)
* site (site name)
* trt (TRT or CTL, for treatment or control)
* position (top or bottom of prairie strip, control well is always at bottom)
* Sample Source (generated by water quality lab and is not used)
* Date (generated by water quality lab and is not used)
* ID# (4-digit code generated by water quality lab and refers to the id number in the "groundwater.csv" file)