---
title: "tablesforstrips2018"
author: "witte"
date: "January 4, 2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
require(knitr)
require(kableExtra)
require(dplyr)
```
```{r, echo=FALSE}
rainrun2018 <- read.csv("C:/Users/Chris/Documents/prairiestrips/tables/rainrunoff2018.csv")
kable(rainrun2018, caption = "Table 1: Rain and surface runoff cumulative totals (inches) for 2018") %>%
  kable_styling(full_width = F, position = "left") %>%
  add_header_above(c(" " = 1, " " = 1, "Runoff" = 2))

nutrients2018 <- read.csv("C:/Users/Chris/Documents/prairiestrips/tables/nutrients2018.csv")
kable(nutrients2018, caption = "Table 2: Cumulative totals (lbs/ac) for measured nutrients exported from field in 2018", 
      col.names = c("Site", "Control", "Treatment", "Control", "Treatment", "Control", "Treatment")) %>%
  kable_styling(full_width = F, position = "left") %>%
  add_header_above(c(" " = 1, "Nitrate + Nitrite" = 2, "Orthophosphate" = 2, "Total Suspended Solids" = 2))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
